name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show toolchain
        run: |
          uname -a
          as --version | head -n 1
          ld --version | head -n 1
          python3 --version

      - name: Build and test
        run: make clean && make test
